---
- hosts: all
  become: yes
  become_exe: "sudo su -"
  become_method: su
  tasks:

    - name: Install Java 17
      apt:
        name: openjdk-17-jdk
        state: present
      when: ansible_os_family == "Debian" and ansible_distribution_version == "18.04" or ansible_distribution_version == "20.04"

    - name: Install Java 17 u16 1
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - software-properties-common
        - wget
      when: ansible_os_family == "Debian" and ansible_distribution_version == "16.04"

    - name: Install Java 17 u16 2
      shell: wget https://download.oracle.com/java/17/latest/jdk-17_linux-x64_bin.deb
      when: ansible_os_family == "Debian" and ansible_distribution_version == "16.04"

    - name: Install Java 17 u16 3
      shell: sudo apt install ./jdk-17_linux-x64_bin.deb -y
      when: ansible_os_family == "Debian" and ansible_distribution_version == "16.04"

    - name: Install Java 17 u16
      shell: sudo update-alternatives --install "/usr/bin/java" "java" "/usr/lib/jvm/jdk-17/bin/java" 1
      #      ignore_error: yes
      when: ansible_os_family == "Debian" and ansible_distribution_version == "16.04"

    - name: Install Java 17 u16 4
      shell: 'sudo update-alternatives --set java /usr/lib/jvm/jdk-17/bin/java'
      when: ansible_os_family == "Debian" and ansible_distribution_version == "16.04"

    - name: Install Java 17
      yum:
        name: wget
        state: present
      when: ansible_distribution == "CentOS" and ansible_distribution_major_version  == "7" or ansible_distribution_major_version  == "8"

    - name: Install Java 17
      shell: wget https://download.oracle.com/java/17/latest/jdk-17_linux-x64_bin.rpm
      when: ansible_distribution == "CentOS" and ansible_distribution_major_version  == "7" or ansible_distribution_major_version  == "8"

    - name: Install Java 17
      shell: rpm -ivh jdk-17_linux-x64_bin.rpm
      when: ansible_distribution == "CentOS" and ansible_distribution_major_version  == "7" or ansible_distribution_major_version  == "8"
