---
- hosts: all
  become: yes
  become_exe: "sudo su -"
  become_method: su
  tasks:

    - name: Install Java 11
      apt:
        name: openjdk-11-jdk
        state: present
      when: ansible_os_family == "Debian" and  ansible_distribution_version == "18.04" or ansible_distribution_version == "20.04"

    - name: Install Java 11 u16
      apt:
        name: software-properties-common
        state: present
      when: ansible_os_family == "Debian" and ansible_distribution_version == "16.04"

    - name: Install Java 11 u16
      shell: echo -ne '\n' | add-apt-repository ppa:openjdk-r/ppa
      when: ansible_os_family == "Debian" and ansible_distribution_version == "16.04"

    - name: Install Java 11 u16
      shell: apt-get update
      when: ansible_os_family == "Debian" and ansible_distribution_version == "16.04"

    - name: Install Java 11 u16
      apt:
        name: openjdk-11-jdk
        state: present
      when: ansible_os_family == "Debian" and ansible_distribution_version == "16.04"


    - name: Install Java 11
      yum:
        name: java-11-openjdk-devel
        state: present
      when: ansible_distribution == "CentOS" and ansible_distribution_major_version  == "7" or ansible_distribution_major_version  == "8"
