---
- hosts: all
  become: yes
  become_exe: "sudo su -"
  become_method: su
  tasks:

    - name: Install Nginx 1.18
      apt:
        name: nginx
        state: present
      when: ansible_os_family == "Debian" and ansible_distribution_version == "16.04" or ansible_distribution_version == "18.04" or ansible_distribution_version == "20.04"

    - name: Install Nginx 1.18
      shell: sudo service nginx start
      when: ansible_os_family == "Debian" and ansible_distribution_version == "16.04" or ansible_distribution_version == "18.04" or ansible_distribution_version == "20.04"

    - name: restart-nginx
      service:
        name: nginx
        state: started
      when: ansible_os_family == "Debian" and ansible_distribution_version == "16.04" or ansible_distribution_version == "18.04" or ansible_distribution_version == "20.04"

    - name: Install Nginx 1.18
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - epel-release
        - nginx
      when: ansible_distribution == "CentOS" and ansible_distribution_major_version  == "7" or ansible_distribution_major_version  == "8"

    - name: restart-nginx
      service:
        name: nginx
        state: restarted
      when: ansible_distribution == "CentOS" and ansible_distribution_major_version  == "7" or ansible_distribution_major_version  == "8"
