---
- hosts: all
  become: yes
  become_exe: "sudo su -"
  become_method: su
  tasks:

    - name: Install node 12
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - curl 
        - dirmngr 
        - apt-transport-https
        - lsb-release
        - ca-certificates  
      when: ansible_os_family == "Debian" and ansible_distribution_version == "16.04" or ansible_distribution_version == "18.04" or ansible_distribution_version == "20.04"

    - name: Install node 12 
      shell: curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
      when: ansible_os_family == "Debian" and ansible_distribution_version == "16.04" or ansible_distribution_version == "18.04" or ansible_distribution_version == "20.04"

    - name: Install node 12 
      apt:
        name: "{{ item }}"
        state: present 
      loop:
        - nodejs
        - gcc 
        - g++
        - make                   
      when: ansible_os_family == "Debian" and ansible_distribution_version == "16.04" or ansible_distribution_version == "18.04" or ansible_distribution_version == "20.04"
            
    - name: Install node 12
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - curl
        - gcc-c++
        - make  
      when: ansible_distribution == "CentOS" and ansible_distribution_major_version  == "7" or ansible_distribution_major_version  == "8"

    - name: Install node 12
      shell: curl -sL https://rpm.nodesource.com/setup_12.x -o nodesource_setup.sh
      when: ansible_distribution == "CentOS" and ansible_distribution_major_version  == "7" or ansible_distribution_major_version  == "8"      

    - name: Install node 12
      shell: bash nodesource_setup.sh && rm -rf nodesource_setup.sh
      when: ansible_distribution == "CentOS" and ansible_distribution_major_version  == "7" or ansible_distribution_major_version  == "8"   

    - name: Install node 12
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - nodejs-12.22.7
      when: ansible_distribution == "CentOS" and ansible_distribution_major_version  == "7" or ansible_distribution_major_version  == "8"

    - name: Install node 12
      shell: npm install -y npm@8.2.0 --global
      when: ansible_distribution == "CentOS" and ansible_distribution_major_version  == "7" or ansible_distribution_major_version  == "8"    